// =============================================================================
//  emojiData.js — a curated set of common emoji for the composer picker.
//
//  Native Unicode only: every entry is a plain string of codepoints rendered by
//  the OS emoji font. No images, no sprite sheets, no external dataset — so this
//  ships as ~a few KB of text and never trips the "no images" content policy or
//  the artifact CSP. Each item is { c: char, n: search name }. Search matches a
//  case-insensitive substring of `n`, so keep names lowercase and descriptive.
//
//  This is intentionally a well-covered common set (~300), not the full 3,600+
//  Unicode emoji — it's the fast, tidy 90% picker. Easy to extend: add items to
//  a category (or a new category) and they appear automatically.
// =============================================================================

export const EMOJI_CATEGORIES = [
  {
    id: 'smileys',
    label: 'Smileys',
    items: [
      { c: '😀', n: 'grinning face happy smile' },
      { c: '😃', n: 'smiley happy grin' },
      { c: '😄', n: 'smile happy laugh' },
      { c: '😁', n: 'beaming grin happy' },
      { c: '😆', n: 'laughing lol satisfied' },
      { c: '😅', n: 'sweat smile nervous laugh' },
      { c: '🤣', n: 'rofl rolling laughing' },
      { c: '😂', n: 'joy laughing tears crying' },
      { c: '🙂', n: 'slight smile' },
      { c: '🙃', n: 'upside down silly' },
      { c: '😉', n: 'wink' },
      { c: '😊', n: 'blush smile happy' },
      { c: '😇', n: 'innocent halo angel' },
      { c: '🥰', n: 'love hearts adore' },
      { c: '😍', n: 'heart eyes love' },
      { c: '🤩', n: 'star struck amazed' },
      { c: '😘', n: 'kiss blowing heart' },
      { c: '😗', n: 'kissing' },
      { c: '😚', n: 'kissing closed eyes' },
      { c: '😙', n: 'kissing smiling' },
      { c: '😋', n: 'yum tasty tongue' },
      { c: '😛', n: 'tongue out' },
      { c: '😜', n: 'wink tongue joke' },
      { c: '🤪', n: 'zany goofy wild' },
      { c: '😝', n: 'squinting tongue' },
      { c: '🤑', n: 'money mouth rich' },
      { c: '🤗', n: 'hug hugging' },
      { c: '🤭', n: 'hand over mouth oops giggle' },
      { c: '🤫', n: 'shush quiet secret' },
      { c: '🤔', n: 'thinking hmm' },
      { c: '🤐', n: 'zipper mouth quiet' },
      { c: '🤨', n: 'raised eyebrow skeptical' },
      { c: '😐', n: 'neutral meh' },
      { c: '😑', n: 'expressionless blank' },
      { c: '😶', n: 'no mouth silent' },
      { c: '😏', n: 'smirk smug' },
      { c: '😒', n: 'unamused annoyed' },
      { c: '🙄', n: 'eye roll' },
      { c: '😬', n: 'grimace awkward' },
      { c: '🤥', n: 'lying liar' },
      { c: '😌', n: 'relieved calm' },
      { c: '😔', n: 'pensive sad' },
      { c: '😪', n: 'sleepy tired' },
      { c: '🤤', n: 'drool' },
      { c: '😴', n: 'sleeping zzz' },
      { c: '😷', n: 'mask sick' },
      { c: '🤒', n: 'thermometer sick ill' },
      { c: '🤕', n: 'bandage hurt injured' },
      { c: '🤢', n: 'nauseated sick gross' },
      { c: '🤮', n: 'vomit puke sick' },
      { c: '🤧', n: 'sneeze tissue' },
      { c: '🥵', n: 'hot heat sweating' },
      { c: '🥶', n: 'cold freezing' },
      { c: '🥴', n: 'woozy dizzy drunk' },
      { c: '😵', n: 'dizzy knocked out' },
      { c: '🤯', n: 'mind blown exploding head' },
      { c: '🤠', n: 'cowboy' },
      { c: '🥳', n: 'party celebrate hat' },
      { c: '😎', n: 'cool sunglasses' },
      { c: '🤓', n: 'nerd geek glasses' },
      { c: '🧐', n: 'monocle inspect' },
      { c: '😕', n: 'confused' },
      { c: '😟', n: 'worried' },
      { c: '🙁', n: 'slight frown sad' },
      { c: '😮', n: 'open mouth wow surprised' },
      { c: '😯', n: 'hushed surprised' },
      { c: '😲', n: 'astonished shocked' },
      { c: '😳', n: 'flushed embarrassed' },
      { c: '🥺', n: 'pleading puppy eyes' },
      { c: '😦', n: 'frowning open mouth' },
      { c: '😧', n: 'anguished' },
      { c: '😨', n: 'fearful scared' },
      { c: '😰', n: 'anxious sweat' },
      { c: '😥', n: 'sad relieved disappointed' },
      { c: '😢', n: 'cry sad tear' },
      { c: '😭', n: 'sobbing bawling cry' },
      { c: '😱', n: 'scream shocked fear' },
      { c: '😖', n: 'confounded frustrated' },
      { c: '😣', n: 'persevere struggle' },
      { c: '😞', n: 'disappointed sad' },
      { c: '😓', n: 'downcast sweat' },
      { c: '😩', n: 'weary tired' },
      { c: '😫', n: 'tired exhausted' },
      { c: '🥱', n: 'yawn bored' },
      { c: '😤', n: 'triumph huff frustrated' },
      { c: '😡', n: 'angry rage mad' },
      { c: '😠', n: 'angry mad' },
      { c: '🤬', n: 'cursing swearing angry' },
      { c: '😈', n: 'devil smiling imp' },
      { c: '👿', n: 'angry devil imp' },
      { c: '💀', n: 'skull dead' },
      { c: '💩', n: 'poop' },
      { c: '🤡', n: 'clown' },
      { c: '👻', n: 'ghost boo' },
      { c: '👽', n: 'alien' },
      { c: '🤖', n: 'robot bot' },
      { c: '🎃', n: 'jack o lantern pumpkin halloween' },
    ],
  },
  {
    id: 'gestures',
    label: 'Gestures',
    items: [
      { c: '👍', n: 'thumbs up like yes approve' },
      { c: '👎', n: 'thumbs down dislike no' },
      { c: '👌', n: 'ok perfect' },
      { c: '🤌', n: 'pinched fingers italian' },
      { c: '🤏', n: 'pinch small' },
      { c: '✌️', n: 'victory peace' },
      { c: '🤞', n: 'fingers crossed luck' },
      { c: '🤟', n: 'love you gesture' },
      { c: '🤘', n: 'rock horns metal' },
      { c: '🤙', n: 'call me shaka' },
      { c: '👈', n: 'point left' },
      { c: '👉', n: 'point right' },
      { c: '👆', n: 'point up' },
      { c: '👇', n: 'point down' },
      { c: '☝️', n: 'index up' },
      { c: '✋', n: 'raised hand stop' },
      { c: '🤚', n: 'raised back of hand' },
      { c: '🖐️', n: 'hand fingers splayed' },
      { c: '🖖', n: 'vulcan spock' },
      { c: '👋', n: 'wave hello hi bye' },
      { c: '🤝', n: 'handshake deal agree' },
      { c: '👏', n: 'clap applause' },
      { c: '🙌', n: 'raising hands praise celebrate' },
      { c: '👐', n: 'open hands' },
      { c: '🤲', n: 'palms up' },
      { c: '🙏', n: 'pray thanks please' },
      { c: '✊', n: 'raised fist' },
      { c: '👊', n: 'fist bump punch' },
      { c: '🤛', n: 'left fist' },
      { c: '🤜', n: 'right fist' },
      { c: '💪', n: 'muscle strong flex' },
      { c: '🫰', n: 'finger heart money' },
      { c: '🫶', n: 'heart hands love' },
      { c: '👀', n: 'eyes looking' },
      { c: '🧠', n: 'brain smart' },
    ],
  },
  {
    id: 'hearts',
    label: 'Hearts',
    items: [
      { c: '❤️', n: 'red heart love' },
      { c: '🧡', n: 'orange heart' },
      { c: '💛', n: 'yellow heart' },
      { c: '💚', n: 'green heart' },
      { c: '💙', n: 'blue heart' },
      { c: '💜', n: 'purple heart' },
      { c: '🖤', n: 'black heart' },
      { c: '🤍', n: 'white heart' },
      { c: '🤎', n: 'brown heart' },
      { c: '💔', n: 'broken heart' },
      { c: '❣️', n: 'heart exclamation' },
      { c: '💕', n: 'two hearts love' },
      { c: '💞', n: 'revolving hearts' },
      { c: '💓', n: 'beating heart' },
      { c: '💗', n: 'growing heart' },
      { c: '💖', n: 'sparkling heart' },
      { c: '💘', n: 'heart arrow cupid' },
      { c: '💝', n: 'heart gift ribbon' },
      { c: '💟', n: 'heart decoration' },
      { c: '❤️‍🔥', n: 'heart on fire' },
      { c: '💯', n: 'hundred perfect score' },
      { c: '💥', n: 'boom collision' },
      { c: '💫', n: 'dizzy stars' },
      { c: '💦', n: 'sweat water splash' },
      { c: '💨', n: 'dash wind fast' },
      { c: '🔥', n: 'fire lit hot' },
      { c: '✨', n: 'sparkles shine' },
      { c: '⭐', n: 'star' },
      { c: '🌟', n: 'glowing star' },
      { c: '💤', n: 'zzz sleep' },
    ],
  },
  {
    id: 'animals',
    label: 'Animals',
    items: [
      { c: '🐶', n: 'dog puppy' },
      { c: '🐱', n: 'cat kitten' },
      { c: '🐭', n: 'mouse' },
      { c: '🐹', n: 'hamster' },
      { c: '🐰', n: 'rabbit bunny' },
      { c: '🦊', n: 'fox' },
      { c: '🐻', n: 'bear' },
      { c: '🐼', n: 'panda' },
      { c: '🐨', n: 'koala' },
      { c: '🐯', n: 'tiger' },
      { c: '🦁', n: 'lion' },
      { c: '🐮', n: 'cow' },
      { c: '🐷', n: 'pig' },
      { c: '🐸', n: 'frog' },
      { c: '🐵', n: 'monkey' },
      { c: '🐔', n: 'chicken' },
      { c: '🐧', n: 'penguin' },
      { c: '🐦', n: 'bird' },
      { c: '🦅', n: 'eagle' },
      { c: '🦉', n: 'owl' },
      { c: '🦇', n: 'bat' },
      { c: '🐺', n: 'wolf' },
      { c: '🐗', n: 'boar' },
      { c: '🐴', n: 'horse' },
      { c: '🦄', n: 'unicorn' },
      { c: '🐝', n: 'bee' },
      { c: '🐛', n: 'bug caterpillar' },
      { c: '🦋', n: 'butterfly' },
      { c: '🐌', n: 'snail' },
      { c: '🐞', n: 'ladybug' },
      { c: '🐢', n: 'turtle' },
      { c: '🐍', n: 'snake' },
      { c: '🦖', n: 'dinosaur trex' },
      { c: '🐙', n: 'octopus' },
      { c: '🦑', n: 'squid' },
      { c: '🦀', n: 'crab' },
      { c: '🐠', n: 'fish tropical' },
      { c: '🐟', n: 'fish' },
      { c: '🐬', n: 'dolphin' },
      { c: '🐳', n: 'whale' },
      { c: '🦈', n: 'shark' },
      { c: '🐊', n: 'crocodile alligator' },
      { c: '🐘', n: 'elephant' },
      { c: '🦍', n: 'gorilla' },
      { c: '🐪', n: 'camel' },
      { c: '🐿️', n: 'chipmunk squirrel' },
      { c: '🦔', n: 'hedgehog' },
      { c: '🌵', n: 'cactus' },
      { c: '🌲', n: 'evergreen tree' },
      { c: '🌳', n: 'tree' },
      { c: '🌴', n: 'palm tree' },
      { c: '🌱', n: 'seedling sprout' },
      { c: '🍀', n: 'four leaf clover luck' },
      { c: '🌿', n: 'herb leaves' },
      { c: '🍁', n: 'maple leaf autumn' },
      { c: '🌸', n: 'cherry blossom flower' },
      { c: '🌹', n: 'rose flower' },
      { c: '🌻', n: 'sunflower' },
      { c: '🌼', n: 'blossom flower' },
      { c: '🌷', n: 'tulip' },
    ],
  },
  {
    id: 'food',
    label: 'Food',
    items: [
      { c: '🍎', n: 'apple red' },
      { c: '🍏', n: 'green apple' },
      { c: '🍌', n: 'banana' },
      { c: '🍉', n: 'watermelon' },
      { c: '🍇', n: 'grapes' },
      { c: '🍓', n: 'strawberry' },
      { c: '🫐', n: 'blueberries' },
      { c: '🍒', n: 'cherries' },
      { c: '🍑', n: 'peach' },
      { c: '🥭', n: 'mango' },
      { c: '🍍', n: 'pineapple' },
      { c: '🥥', n: 'coconut' },
      { c: '🥝', n: 'kiwi' },
      { c: '🍅', n: 'tomato' },
      { c: '🥑', n: 'avocado' },
      { c: '🍆', n: 'eggplant aubergine' },
      { c: '🥕', n: 'carrot' },
      { c: '🌽', n: 'corn' },
      { c: '🌶️', n: 'hot pepper chili spicy' },
      { c: '🥔', n: 'potato' },
      { c: '🍞', n: 'bread' },
      { c: '🥐', n: 'croissant' },
      { c: '🥯', n: 'bagel' },
      { c: '🧀', n: 'cheese' },
      { c: '🥚', n: 'egg' },
      { c: '🍳', n: 'fried egg cooking' },
      { c: '🥞', n: 'pancakes' },
      { c: '🥓', n: 'bacon' },
      { c: '🍔', n: 'burger hamburger' },
      { c: '🍟', n: 'fries chips' },
      { c: '🍕', n: 'pizza' },
      { c: '🌭', n: 'hot dog' },
      { c: '🌮', n: 'taco' },
      { c: '🌯', n: 'burrito' },
      { c: '🥗', n: 'salad' },
      { c: '🍝', n: 'pasta spaghetti' },
      { c: '🍜', n: 'ramen noodles' },
      { c: '🍣', n: 'sushi' },
      { c: '🍤', n: 'shrimp tempura' },
      { c: '🍚', n: 'rice' },
      { c: '🍰', n: 'cake slice' },
      { c: '🎂', n: 'birthday cake' },
      { c: '🧁', n: 'cupcake' },
      { c: '🍩', n: 'donut doughnut' },
      { c: '🍪', n: 'cookie' },
      { c: '🍫', n: 'chocolate' },
      { c: '🍬', n: 'candy sweet' },
      { c: '🍭', n: 'lollipop' },
      { c: '🍦', n: 'ice cream soft serve' },
      { c: '🍨', n: 'ice cream bowl' },
      { c: '☕', n: 'coffee tea hot' },
      { c: '🍵', n: 'tea green matcha' },
      { c: '🧋', n: 'bubble tea boba' },
      { c: '🥤', n: 'soda drink cup' },
      { c: '🍺', n: 'beer' },
      { c: '🍻', n: 'beers cheers' },
      { c: '🍷', n: 'wine' },
      { c: '🥂', n: 'champagne cheers celebrate' },
      { c: '🍸', n: 'cocktail martini' },
      { c: '🥃', n: 'whiskey' },
      { c: '🍾', n: 'champagne bottle pop' },
    ],
  },
  {
    id: 'activity',
    label: 'Activity',
    items: [
      { c: '⚽', n: 'soccer football' },
      { c: '🏀', n: 'basketball' },
      { c: '🏈', n: 'american football' },
      { c: '⚾', n: 'baseball' },
      { c: '🎾', n: 'tennis' },
      { c: '🏐', n: 'volleyball' },
      { c: '🏉', n: 'rugby' },
      { c: '🎱', n: 'pool 8 ball billiards' },
      { c: '🏓', n: 'ping pong table tennis' },
      { c: '🏸', n: 'badminton' },
      { c: '🥅', n: 'goal net' },
      { c: '⛳', n: 'golf flag' },
      { c: '🏹', n: 'archery bow' },
      { c: '🎣', n: 'fishing' },
      { c: '🥊', n: 'boxing glove' },
      { c: '🎿', n: 'ski' },
      { c: '⛸️', n: 'ice skate' },
      { c: '🏂', n: 'snowboard' },
      { c: '🏄', n: 'surfing' },
      { c: '🚴', n: 'cycling bike' },
      { c: '🏆', n: 'trophy win champion' },
      { c: '🥇', n: 'gold medal first' },
      { c: '🥈', n: 'silver medal second' },
      { c: '🥉', n: 'bronze medal third' },
      { c: '🏅', n: 'medal' },
      { c: '🎯', n: 'target bullseye dart' },
      { c: '🎮', n: 'video game controller' },
      { c: '🎲', n: 'dice game' },
      { c: '🎰', n: 'slot machine' },
      { c: '🎨', n: 'art palette paint' },
      { c: '🎭', n: 'theater drama masks' },
      { c: '🎬', n: 'movie clapper film' },
      { c: '🎤', n: 'microphone sing' },
      { c: '🎧', n: 'headphones music' },
      { c: '🎵', n: 'music note' },
      { c: '🎶', n: 'music notes' },
      { c: '🎸', n: 'guitar' },
      { c: '🎹', n: 'piano keyboard' },
      { c: '🥁', n: 'drum' },
      { c: '🎺', n: 'trumpet' },
      { c: '🎉', n: 'party tada celebrate' },
      { c: '🎊', n: 'confetti ball' },
      { c: '🎈', n: 'balloon' },
      { c: '🎁', n: 'gift present' },
    ],
  },
  {
    id: 'travel',
    label: 'Travel',
    items: [
      { c: '🚗', n: 'car' },
      { c: '🚕', n: 'taxi' },
      { c: '🚙', n: 'suv' },
      { c: '🚌', n: 'bus' },
      { c: '🏎️', n: 'race car' },
      { c: '🚓', n: 'police car' },
      { c: '🚑', n: 'ambulance' },
      { c: '🚒', n: 'fire truck' },
      { c: '🚚', n: 'truck delivery' },
      { c: '🚜', n: 'tractor' },
      { c: '🛵', n: 'scooter moped' },
      { c: '🏍️', n: 'motorcycle' },
      { c: '🚲', n: 'bicycle bike' },
      { c: '✈️', n: 'plane flight travel' },
      { c: '🚀', n: 'rocket launch space' },
      { c: '🛸', n: 'ufo flying saucer' },
      { c: '🚁', n: 'helicopter' },
      { c: '⛵', n: 'sailboat' },
      { c: '🚤', n: 'speedboat' },
      { c: '🛳️', n: 'ship cruise' },
      { c: '🚂', n: 'train locomotive' },
      { c: '🚆', n: 'train' },
      { c: '🗺️', n: 'map world' },
      { c: '🗽', n: 'statue of liberty' },
      { c: '🗼', n: 'tower tokyo' },
      { c: '🏰', n: 'castle' },
      { c: '🏝️', n: 'island beach' },
      { c: '🏔️', n: 'mountain snow' },
      { c: '🌋', n: 'volcano' },
      { c: '🏕️', n: 'camping tent' },
      { c: '🏠', n: 'house home' },
      { c: '🏢', n: 'office building' },
      { c: '🌆', n: 'city sunset' },
      { c: '🌃', n: 'city night stars' },
      { c: '🌅', n: 'sunrise' },
      { c: '🌄', n: 'sunrise mountains' },
      { c: '🎡', n: 'ferris wheel' },
      { c: '🎢', n: 'roller coaster' },
      { c: '⛲', n: 'fountain' },
    ],
  },
  {
    id: 'objects',
    label: 'Objects',
    items: [
      { c: '⌚', n: 'watch time' },
      { c: '📱', n: 'phone mobile' },
      { c: '💻', n: 'laptop computer' },
      { c: '⌨️', n: 'keyboard' },
      { c: '🖥️', n: 'desktop computer monitor' },
      { c: '🖨️', n: 'printer' },
      { c: '🖱️', n: 'mouse computer' },
      { c: '💾', n: 'floppy disk save' },
      { c: '💿', n: 'cd disc' },
      { c: '📷', n: 'camera photo' },
      { c: '📸', n: 'camera flash' },
      { c: '📹', n: 'video camera' },
      { c: '🎥', n: 'movie camera' },
      { c: '📺', n: 'tv television' },
      { c: '📻', n: 'radio' },
      { c: '☎️', n: 'telephone' },
      { c: '🔋', n: 'battery' },
      { c: '🔌', n: 'plug power' },
      { c: '💡', n: 'light bulb idea' },
      { c: '🔦', n: 'flashlight torch' },
      { c: '🕯️', n: 'candle' },
      { c: '💸', n: 'money flying cash' },
      { c: '💵', n: 'dollar cash money' },
      { c: '💰', n: 'money bag' },
      { c: '💳', n: 'credit card' },
      { c: '🪙', n: 'coin' },
      { c: '💎', n: 'diamond gem' },
      { c: '⚖️', n: 'scales balance justice' },
      { c: '🔧', n: 'wrench tool' },
      { c: '🔨', n: 'hammer' },
      { c: '🛠️', n: 'tools' },
      { c: '⚙️', n: 'gear settings' },
      { c: '🔑', n: 'key' },
      { c: '🔒', n: 'lock locked' },
      { c: '🔓', n: 'unlock open' },
      { c: '🔗', n: 'link chain' },
      { c: '📌', n: 'pin pushpin' },
      { c: '📎', n: 'paperclip' },
      { c: '✂️', n: 'scissors cut' },
      { c: '📝', n: 'memo note write' },
      { c: '✏️', n: 'pencil write' },
      { c: '🖊️', n: 'pen write' },
      { c: '📖', n: 'book open read' },
      { c: '📚', n: 'books' },
      { c: '📰', n: 'newspaper news' },
      { c: '📅', n: 'calendar date' },
      { c: '📈', n: 'chart up growth' },
      { c: '📉', n: 'chart down decline' },
      { c: '📊', n: 'bar chart stats' },
      { c: '🔍', n: 'search magnify' },
      { c: '💊', n: 'pill medicine' },
      { c: '🩺', n: 'stethoscope doctor' },
      { c: '🎓', n: 'graduation cap education' },
      { c: '👑', n: 'crown king royal' },
      { c: '🧭', n: 'compass' },
      { c: '⏰', n: 'alarm clock' },
      { c: '⏳', n: 'hourglass time' },
      { c: '🧨', n: 'firecracker dynamite' },
    ],
  },
  {
    id: 'symbols',
    label: 'Symbols',
    items: [
      { c: '✅', n: 'check mark done yes' },
      { c: '❌', n: 'cross x no wrong' },
      { c: '❎', n: 'cross check' },
      { c: '➕', n: 'plus add' },
      { c: '➖', n: 'minus subtract' },
      { c: '✔️', n: 'check tick' },
      { c: '☑️', n: 'checkbox ticked' },
      { c: '⚠️', n: 'warning caution' },
      { c: '🚫', n: 'no prohibited forbidden' },
      { c: '❗', n: 'exclamation important' },
      { c: '❓', n: 'question' },
      { c: '💭', n: 'thought bubble' },
      { c: '💬', n: 'speech bubble comment' },
      { c: '🗯️', n: 'anger speech bubble' },
      { c: '🔔', n: 'bell notification' },
      { c: '🔕', n: 'mute bell off' },
      { c: '📣', n: 'megaphone announce' },
      { c: '📢', n: 'loudspeaker announce' },
      { c: '♻️', n: 'recycle' },
      { c: '⚡', n: 'lightning bolt zap electric' },
      { c: '☀️', n: 'sun sunny' },
      { c: '🌙', n: 'moon crescent night' },
      { c: '⭐', n: 'star' },
      { c: '🌈', n: 'rainbow' },
      { c: '☁️', n: 'cloud' },
      { c: '⛅', n: 'partly cloudy sun' },
      { c: '🌧️', n: 'rain cloud' },
      { c: '⛈️', n: 'thunderstorm' },
      { c: '❄️', n: 'snowflake cold' },
      { c: '☃️', n: 'snowman' },
      { c: '💧', n: 'droplet water' },
      { c: '🌊', n: 'wave ocean water' },
      { c: '🏳️', n: 'white flag' },
      { c: '🏴', n: 'black flag' },
      { c: '🏁', n: 'checkered flag finish' },
      { c: '🚩', n: 'red flag' },
      { c: '➡️', n: 'right arrow' },
      { c: '⬅️', n: 'left arrow' },
      { c: '⬆️', n: 'up arrow' },
      { c: '⬇️', n: 'down arrow' },
      { c: '🔞', n: 'no under 18 adult' },
      { c: '♾️', n: 'infinity forever' },
    ],
  },
]

// Flat list for search, computed once.
export const EMOJI_FLAT = EMOJI_CATEGORIES.flatMap((cat) =>
  cat.items.map((it) => ({ ...it, cat: cat.id })),
)
